### ISSUE TITLE
Toggle lights to "standard" state, not to last state

### ISSUE THREAD

**Issue by Aephir** [Aephir/HomeAssistant2#18]
E.g. in floorplan and HADashboard, there it only a toggle that is easy to use. But if the last time the light was on, it was at 10%, then the toggle will turn on the light at 10%. It needs to turn on to a "standard" state when toggle on.

One solution could be as frosty22 describes here:
https://community.home-assistant.io/t/how-to-use-toggle-and-go-to-full-brightness-when-turning-on/6513/7

```
script:
  toggle_to_off:
    sequence:
      - condition: template
        value_template: '{{ is_state(light, "on") }}'
      - service: light.turn_off
        data_template:
          entity_id: "{{ light }}"

  toggle_to_on:
    sequence:
      - condition: template
        value_template: '{{ is_state(light, "off") and (as_timestamp(now()) - as_timestamp(states.light[light|replace("light.","")].last_changed) > 3) }}'
      - service: light.turn_on
        data_template:
          entity_id: "{{ light }}"
          brightness_pct: 100

  toggle_to_max:
    sequence:
      - service: script.toggle_to_off
        data_template:
          light: "{{ light }}"
      - service: script.toggle_to_on
        data_template:
          light: "{{ light }}"
```
and call in automation by
```
action:
  service: script.toggle_to_max
  data:
    light: light.bedroom
```
